apiVersion: batch/v1
kind: Job
metadata:
  name: alembic-migration
spec:
  template:
    spec:
      containers:
        - name: alembic
          image: IMAGE_PLACEHOLDER
          command: ["alembic"]
          args: ["upgrade", "head"]
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DATABASE_URL
      restartPolicy: Never
  backoffLimit: 2
