version: "3.7"

services:
  clickhouse-server:
    image: yandex/clickhouse-server:latest
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    networks:
      - clickhouse-net

networks:
  clickhouse-net:
    driver: bridge
