[tool.poetry]
name = "exchange-data-collector"
version = "0.1.0"
description = ""
authors = ["Shadow Insights"]

[tool.poetry.dependencies]
python = "^3.10"
python-dotenv = "^1.0.0"
pydantic-settings = "^2.0.1"
httpx = "^0.24.1"
websockets = "^11.0.3"
clickhouse-driver = "^0.2.6"
prometheus-client = "^0.17.1"

[tool.poetry.dev-dependencies]
isort = "^5.12.0"
black = "^23.7.0"
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 79
