"""empty message

Revision ID: 09f683de22c4
Revises: a948506bbcbf
Create Date: 2023-12-25 19:49:08.496693

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "09f683de22c4"
down_revision: Union[str, None] = "a948506bbcbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apy_asset",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("exchange_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchanges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "apy",
        sa.Column("apy", sa.DECIMAL(), nullable=False),
        sa.Column("launch_id", sa.UUID(), nullable=False),
        sa.Column("apy_asset_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["apy_asset_id"],
            ["apy_asset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_apy_launch_id"), "apy", ["launch_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_apy_launch_id"), table_name="apy")
    op.drop_table("apy")
    op.drop_table("apy_asset")
    # ### end Alembic commands ###
