"""empty message

Revision ID: 11075bc00836
Revises: ab0377b29e73
Create Date: 2023-11-12 13:27:11.424455

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "11075bc00836"
down_revision: Union[str, None] = "ab0377b29e73"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "volumes",
        sa.Column("average_volume", sa.Integer(), nullable=False),
        sa.Column("launch_id", sa.UUID(), nullable=False),
        sa.Column("pair_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pair_id"],
            ["pairs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_volumes_launch_id"), "volumes", ["launch_id"], unique=False
    )
    op.drop_index("ix_volume_launch_id", table_name="volume")
    op.drop_table("volume")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "volume",
        sa.Column(
            "average_volume", sa.INTEGER(), autoincrement=False, nullable=False
        ),
        sa.Column("launch_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("pair_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP(0)"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pair_id"], ["pairs.id"], name="volume_pair_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="volume_pkey"),
    )
    op.create_index(
        "ix_volume_launch_id", "volume", ["launch_id"], unique=False
    )
    op.drop_index(op.f("ix_volumes_launch_id"), table_name="volumes")
    op.drop_table("volumes")
    # ### end Alembic commands ###
