"""empty message

Revision ID: 47392ff809ad
Revises: f066b6042bec
Create Date: 2023-11-01 22:23:53.802446

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "47392ff809ad"
down_revision: Union[str, None] = "f066b6042bec"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "order_book_anomalies",
        sa.Column("launch_id", sa.UUID(), nullable=False),
        sa.Column("pair_id", sa.UUID(), nullable=False),
        sa.Column("price", sa.DECIMAL(), nullable=False),
        sa.Column("quantity", sa.DECIMAL(), nullable=False),
        sa.Column("order_liquidity", sa.DECIMAL(), nullable=False),
        sa.Column("average_liquidity", sa.DECIMAL(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column(
            "type", sa.Enum("ask", "bid", native_enum=False), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pair_id"],
            ["pairs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_book_anomalies_launch_id"),
        "order_book_anomalies",
        ["launch_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_order_book_anomalies_launch_id"),
        table_name="order_book_anomalies",
    )
    op.drop_table("order_book_anomalies")
    # ### end Alembic commands ###
