"""empty message

Revision ID: 4bd4ff963a6c
Revises: 689363f6cbdd
Create Date: 2023-11-26 22:00:14.988111

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4bd4ff963a6c"
down_revision: Union[str, None] = "689363f6cbdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "orders_anomalies_summaries",
        sa.Column("launch_id", sa.UUID(), nullable=False),
        sa.Column("pair_id", sa.UUID(), nullable=False),
        sa.Column("orders_total_difference", sa.DECIMAL(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pair_id"],
            ["pairs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_orders_anomalies_summaries_launch_id"),
        "orders_anomalies_summaries",
        ["launch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_book_anomalies_pair_id"),
        "order_book_anomalies",
        ["pair_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_book_anomalies_type"),
        "order_book_anomalies",
        ["type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_book_anomalies_updated_at"),
        "order_book_anomalies",
        ["updated_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_order_book_anomalies_updated_at"),
        table_name="order_book_anomalies",
    )
    op.drop_index(
        op.f("ix_order_book_anomalies_type"), table_name="order_book_anomalies"
    )
    op.drop_index(
        op.f("ix_order_book_anomalies_pair_id"),
        table_name="order_book_anomalies",
    )
    op.drop_index(
        op.f("ix_orders_anomalies_summaries_launch_id"),
        table_name="orders_anomalies_summaries",
    )
    op.drop_table("orders_anomalies_summaries")
    # ### end Alembic commands ###
