"""empty message

Revision ID: 72cc7bf2aee8
Revises: 22bab56f31a3
Create Date: 2023-11-18 18:48:59.111299

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "72cc7bf2aee8"
down_revision: Union[str, None] = "22bab56f31a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_book_anomalies",
        sa.Column(
            "updated_at", sa.DateTime(), server_default="now()", nullable=True
        ),
    )
    op.execute(
        "UPDATE order_book_anomalies SET is_cancelled = False WHERE is_cancelled IS NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_book_anomalies", "updated_at")
    # ### end Alembic commands ###
