"""empty message

Revision ID: 7461faa17afe
Revises: 689363f6cbdd
Create Date: 2023-12-02 21:42:27.998136

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7461faa17afe"
down_revision: Union[str, None] = "689363f6cbdd"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_pairs_symbol", table_name="pairs")
    op.create_index(op.f("ix_pairs_symbol"), "pairs", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_pairs_symbol"), table_name="pairs")
    op.create_index("ix_pairs_symbol", "pairs", ["symbol"], unique=False)
    # ### end Alembic commands ###
