"""empty message

Revision ID: 74cadc69a285
Revises: f046597a56d5
Create Date: 2023-10-10 21:27:45.656780

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74cadc69a285"
down_revision: Union[str, None] = "f046597a56d5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "liquidity",
        sa.Column("average_volume", sa.Integer(), nullable=False),
        sa.Column("launch_id", sa.UUID(), nullable=False),
        sa.Column("pair_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pair_id"],
            ["pairs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_liquidity_launch_id"),
        "liquidity",
        ["launch_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_liquidity_launch_id"), table_name="liquidity")
    op.drop_table("liquidity")
    # ### end Alembic commands ###
