"""empty message

Revision ID: 9e19ffca1071
Revises: 22bab56f31a3
Create Date: 2023-11-20 00:32:42.477922

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9e19ffca1071"
down_revision: Union[str, None] = "72cc7bf2aee8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "volumes", sa.Column("bid_ask_ratio", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("volumes", "bid_ask_ratio")
    # ### end Alembic commands ###
