"""empty message

Revision ID: a948506bbcbf
Revises: 6957c060dbc1
Create Date: 2023-12-05 14:34:46.303672

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a948506bbcbf"
down_revision: Union[str, None] = "6957c060dbc1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "volumes",
        "bid_ask_ratio",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.DECIMAL(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "volumes",
        "bid_ask_ratio",
        existing_type=sa.DECIMAL(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
