"""empty message

Revision ID: ed028356120a
Revises: 47392ff809ad
Create Date: 2023-11-03 10:51:21.062553

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed028356120a"
down_revision: Union[str, None] = "47392ff809ad"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "order_book_anomalies",
        sa.Column("is_cancelled", sa.Boolean(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("order_book_anomalies", "is_cancelled")
    # ### end Alembic commands ###
