"""empty message

Revision ID: f066b6042bec
Revises: 74cadc69a285
Create Date: 2023-10-22 18:17:27.985649

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f066b6042bec"
down_revision: Union[str, None] = "74cadc69a285"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "maestro_instances",
        sa.Column("launch_id", sa.UUID(), nullable=False),
        sa.Column("latest_liveness_time", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_maestro_instances_latest_liveness_time"),
        "maestro_instances",
        ["latest_liveness_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_maestro_instances_launch_id"),
        "maestro_instances",
        ["launch_id"],
        unique=False,
    )
    op.add_column(
        "pairs", sa.Column("maestro_instance_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        None, "pairs", "maestro_instances", ["maestro_instance_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pairs", type_="foreignkey")
    op.drop_column("pairs", "maestro_instance_id")
    op.drop_index(
        op.f("ix_maestro_instances_launch_id"), table_name="maestro_instances"
    )
    op.drop_index(
        op.f("ix_maestro_instances_latest_liveness_time"),
        table_name="maestro_instances",
    )
    op.drop_table("maestro_instances")
    # ### end Alembic commands ###
