"""init

Revision ID: ffa07a24d006
Revises: 
Create Date: 2023-09-23 16:51:54.802281

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ffa07a24d006"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exchanges",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_exchanges_name"), "exchanges", ["name"], unique=True
    )
    op.create_table(
        "pairs",
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("delimiter", sa.DECIMAL(), nullable=False),
        sa.Column("exchange_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["exchange_id"],
            ["exchanges.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_pairs_symbol"), "pairs", ["symbol"], unique=True)
    op.create_table(
        "order_books",
        sa.Column("launch_id", sa.UUID(), nullable=False),
        sa.Column("stamp_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "order_book",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
        ),
        sa.Column("pair_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("current_timestamp(0)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pair_id"],
            ["pairs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_order_books_launch_id"),
        "order_books",
        ["launch_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_order_books_stamp_id"),
        "order_books",
        ["stamp_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_order_books_stamp_id"), table_name="order_books")
    op.drop_index(op.f("ix_order_books_launch_id"), table_name="order_books")
    op.drop_table("order_books")
    op.drop_index(op.f("ix_pairs_symbol"), table_name="pairs")
    op.drop_table("pairs")
    op.drop_index(op.f("ix_exchanges_name"), table_name="exchanges")
    op.drop_table("exchanges")
    # ### end Alembic commands ###
