apiVersion: apps/v1
kind: Deployment
metadata:
  name: exchange-data-collector
  labels:
    app: exchange-data-collector
spec:
  replicas: 21
  selector:
    matchLabels:
      app: exchange-data-collector
  template:
    metadata:
      labels:
        app: exchange-data-collector
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      containers:
        - name: exchange-data-collector-container
          image: IMAGE_PLACEHOLDER
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
          env:
            - name: POSTGRES_HOST
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_HOST
                  name: exchange-data-collector-config
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_DB
                  name: exchange-data-collector-config
            - name: POSTGRES_PORT
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PORT
                  name: exchange-data-collector-config
            - name: POSTGRES_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_USERNAME
                  name: exchange-data-collector-config
            - name: VOLUME_WORKER_JOB_INTERVAL
              valueFrom:
                configMapKeyRef:
                  key: VOLUME_WORKER_JOB_INTERVAL
                  name: exchange-data-collector-config
            - name: DB_WORKER_JOB_INTERVAL
              valueFrom:
                configMapKeyRef:
                  key: DB_WORKER_JOB_INTERVAL
                  name: exchange-data-collector-config
            - name: VOLUME_COMPARATIVE_ARRAY_SIZE
              valueFrom:
                configMapKeyRef:
                  key: VOLUME_COMPARATIVE_ARRAY_SIZE
                  name: exchange-data-collector-config
            - name: VOLUME_ANOMALY_RATIO
              valueFrom:
                configMapKeyRef:
                  key: VOLUME_ANOMALY_RATIO
                  name: exchange-data-collector-config
            - name: DISCORD_WEBHOOKS
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_WEBHOOKS
                  name: exchange-data-collector-config
            - name: DISCORD_DEPTH_EMBED_COLOR
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_DEPTH_EMBED_COLOR
                  name: exchange-data-collector-config
            - name: ORDERS_WORKER_JOB_INTERVAL
              valueFrom:
                configMapKeyRef:
                  key: ORDERS_WORKER_JOB_INTERVAL
                  name: exchange-data-collector-config
            - name: TOP_N_ORDERS
              valueFrom:
                configMapKeyRef:
                  key: TOP_N_ORDERS
                  name: exchange-data-collector-config
            - name: ORDER_ANOMALY_MULTIPLIER
              valueFrom:
                configMapKeyRef:
                  key: ORDER_ANOMALY_MULTIPLIER
                  name: exchange-data-collector-config
            - name: ANOMALIES_DETECTION_TTL
              valueFrom:
                configMapKeyRef:
                  key: ANOMALIES_DETECTION_TTL
                  name: exchange-data-collector-config
            - name: DISCORD_ORDER_ANOMALY_BID_EMBED_COLOR
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_ORDER_ANOMALY_BID_EMBED_COLOR
                  name: exchange-data-collector-config
            - name: DISCORD_ORDER_ANOMALY_ASK_EMBED_COLOR
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_ORDER_ANOMALY_ASK_EMBED_COLOR
                  name: exchange-data-collector-config
            - name: ANOMALIES_OBSERVING_TTL
              valueFrom:
                configMapKeyRef:
                  key: ANOMALIES_OBSERVING_TTL
                  name: exchange-data-collector-config
            - name: ANOMALIES_OBSERVING_RATIO
              valueFrom:
                configMapKeyRef:
                  key: ANOMALIES_OBSERVING_RATIO
                  name: exchange-data-collector-config
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: POSTGRES_PASSWORD
                  name: exchange-data-collector-config
            - name: IS_TRADING_SESSION_VERIFICATION_REQUIRED
              valueFrom:
                configMapKeyRef:
                  key: IS_TRADING_SESSION_VERIFICATION_REQUIRED
                  name: exchange-data-collector-config
            - name: ORDER_ANOMALY_MINIMUM_LIQUIDITY
              valueFrom:
                configMapKeyRef:
                  key: ORDER_ANOMALY_MINIMUM_LIQUIDITY
                  name: exchange-data-collector-config
            - name: MAXIMUM_ORDER_BOOK_ANOMALIES
              valueFrom:
                configMapKeyRef:
                  key: MAXIMUM_ORDER_BOOK_ANOMALIES
                  name: exchange-data-collector-config
            - name: OBSERVING_SAVED_LIMIT_ANOMALIES_RATIO
              valueFrom:
                configMapKeyRef:
                  key: OBSERVING_SAVED_LIMIT_ANOMALIES_RATIO
                  name: exchange-data-collector-config
            - name: DISCORD_ORDER_BOOK_ANOMALY_CANCELED_EMBED_COLOR
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_ORDER_BOOK_ANOMALY_CANCELED_EMBED_COLOR
                  name: exchange-data-collector-config
            - name: DISCORD_ORDER_BOOK_ANOMALY_REALIZED_EMBED_COLOR
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_ORDER_BOOK_ANOMALY_REALIZED_EMBED_COLOR
                  name: exchange-data-collector-config
            - name: TELEGRAM_BOT_TOKENS
              valueFrom:
                configMapKeyRef:
                  key: TELEGRAM_BOT_TOKENS
                  name: exchange-data-collector-config
            - name: TELEGRAM_CHAT_IDS
              valueFrom:
                configMapKeyRef:
                  key: TELEGRAM_CHAT_IDS
                  name: exchange-data-collector-config
            - name: ORDERS_ANOMALIES_SUMMARY_RATIO
              valueFrom:
                configMapKeyRef:
                  key: ORDERS_ANOMALIES_SUMMARY_RATIO
                  name: exchange-data-collector-config
            - name: ORDERS_ANOMALIES_SUMMARY_COMPARATIVE_ARRAY_SIZE
              valueFrom:
                configMapKeyRef:
                  key: ORDERS_ANOMALIES_SUMMARY_COMPARATIVE_ARRAY_SIZE
                  name: exchange-data-collector-config
            - name: DISCORD_ORDER_ANOMALIES_SUMMARY_EMBED_COLOR
              valueFrom:
                configMapKeyRef:
                  key: DISCORD_ORDER_ANOMALIES_SUMMARY_EMBED_COLOR
                  name: exchange-data-collector-config