name: Python Tests and Linting

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -

      - name: Cache Poetry dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/poetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: |
          poetry install

      - name: Copy .development.env to .env
        run: cp .development.env .env

      - name: Sort imports with isort
        run: |
          poetry run python -m isort .

      - name: Format with black
        run: |
          poetry run python -m black .

      - name: Lint with flake8
        run: |
          poetry run flake8 .

      - name: Check types with mypy
        run: |
          poetry run mypy ./app

      - name: Run unit tests
        run: |
          poetry run pytest
